<a href="https://colab.research.google.com/github/anubhavshrestha/Machine-Learning/blob/main/Recitation_Week5_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4.1 Import numpy as np and see the version

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


## 4.2 How to create a boolean array?

In [ ]:
# Create a 3×3 numpy array of all True’s
np.ones((3,3),dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4.3 How to extract items that satisfy a given condition from 1D array?

In [ ]:
# Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [ ]:
# Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]=-1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 4.4 How to stack two arrays?

In [ ]:
# Stack arrays a and b vertically
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

# method1
np.vstack([a,b])
# method2
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# method1
np.hstack([a,b])
# method2
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 4.5 How to get the common items between two python numpy arrays?

In [ ]:
# Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

### 4.6 How to remove from one array those items that exist in another?

In [ ]:
# From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

### 4.7 How to get the positions where elements of two arrays match?

In [ ]:
# Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)        ## confirm the output of where method

(array([1, 3, 5, 7]),)

### 4.8 How to extract all numbers between a given range from a numpy array?

In [ ]:
# Get all items between 5 and 10 from a.
a = np.arange(15)

# method 1
a[(a>=5) & (a<=10)]

# method 2
index=np.where((a>=5) & (a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

### 4.9 How to swap two rows/columns in a 2d numpy array?

In [ ]:
# Swap columns 1st and 2nd in the array arr.
arr = np.arange(9).reshape(3,3)

arr[:,[1,0,2]]

In [ ]:
# Swap rows 1st and 2nd in the array arr:
arr = np.arange(9).reshape(3,3)

arr[[1,0,2],:]

### 4.10 How to reverse the rows/columns of a 2D array?

In [ ]:
# Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)

arr[[2,1,0],:]

arr[::-1,:]

In [ ]:
# How to reverse the columns of a 2D array?
arr = np.arange(9).reshape(3,3)

arr[:,::-1]

# 4.11 How to replace all values greater than a given value to a given cutoff?

In [ ]:
# From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# method 1
np.clip(a,a_min=10,a_max=30)

# method 2
np.where(a<10,10,np.where(a>30,30,a))

# method 3
a[a<10]=10


[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


# 4.12 How to convert an array of arrays into a flat 1d array?

In [ ]:
# Convert array_of_arrays into a flat linear 1d array.
import numpy as np
arr1 = np.arange(3,7)
arr2 = np.arange(4,8)
arr3 = np.arange(5,9)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

print(np.concatenate(array_of_arrays))
print(array_of_arrays.flatten())

array_of_arrays:  [[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
[3 4 5 6 4 5 6 7 5 6 7 8]
[3 4 5 6 4 5 6 7 5 6 7 8]


### 4.13 How to find the maximum value in each row of a numpy array 2d?

In [ ]:
# Compute the maximum for each row in the given array.

np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

#method 1
np.amax(a,axis=1)

# method 2
np.apply_along_axis(np.max,arr=a,axis=1)


[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

### 4.14 How to compute the min-by-max for each row for a numpy array 2d?

In [ ]:
# Compute the min-by-max for each row for given 2d numpy array.

np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

np.apply_along_axis(lambda x:np.min(x)/np.max(x),arr=a,axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

### 4.15 How to drop all missing values from a numpy array?

In [ ]:
# Drop all nan values from a 1D numpy array
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

### 4.16 How to find the index of n'th repetition of an item in an array

In [ ]:
# Find the index of 5th repetition of number 1 in x.
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

[i for i,v in enumerate(x) if v==1][n-1]


8